### ISSUE TITLE
Add dependencies on the package.json

### ISSUE THREAD

**Issue by rokity** [yogain123/Fake-Backend#1]
Hi

The sample it's cool but if I can add the dependencies on the package it's better.
So I can just clone the repo , run npm install and play it.

Thanks
Riccardo Amadio

**Comment by yogain123** [comment]
No local dependency required . You just need to install json-server globally using command "npm install json-server -g"

**Comment by rokity** [comment]
You can install it in the module, and call it from the scripts.
If you don't want to do that I can do it for you. 
Thanks

**Comment by yogain123** [comment]
Yes Please do it

**Comment by yogain123** [comment]
I actually didn't get you. Can you create a Pull Request and Show me ?

**Comment by rokity** [comment]
Hi

I just finished now if you want to see this is the [repo](https://github.com/rokity/Fake-Backend).

Can I make the pull-request?
Thanks

**Comment by yogain123** [comment]
Yes you can
